export const ADD_PRODUCTS_TO_CART = "ADD_PRODUCTS_TO_CART";
export const REMOVE_PRODUCTS_FROM_CART = "REMOVE_PRODUCTS_FROM_CART";
export const CLEAR_CART = "CLEAR_CART";
export const FILTER_PRODUCTS = "FILTER_PRODUCTS";

// async
export const LOAD_PRODUCTS_START = "LOAD_PRODUCTS_START";
export const LOAD_PRODUCTS_SUCCESS = "LOAD_PRODUCTS_SUCCESS";
export const LOAD_PRODUCTS_FAILED = "LOAD_PRODUCTS_FAILED";